commom: &common
  adapter: postgresql
  encoding: unicode
  username: ta6
  password: root
  host: localhost
  pool: 10
  timeout: 15000
  min_messages: warning

development:
  database: LCC_development
  <<: *common

test:
  database: LCC_test
  <<: *common

production:
  database: LCC_production
  <<: *common
